### ISSUE TITLE
PLS FIC BUMPP

### ISSUE THREAD

**Issue by deodev** [BumpBotDiscord/bugs-suggestions#1]
BUMP NO WROK IN SERBER PLES FIC NOW !!!1?!?!?!?!?1

**Comment by SlowestLoris** [comment]
If you could comment in a language we can all understand our support services would be glad to help out.

**Comment by MisterCookiez** [comment]
In order to help the staff team solve this faster, it would be of *greater* help if you could follow the bugs & suggestion guidelines in the README.md file.
