### ISSUE TITLE
bump no work

### ISSUE THREAD

**Issue by deodev** [BumpBotDiscord/bugs-suggestions#2]
bump no work when put in command! my english bad because im 9!?!

**Comment by MisterCookiez** [comment]
Please put a screenshot, or the message that bump had sent.

**Comment by deodev** [comment]
https://gyazo.com/f8b797874565db3010b31ad1eb510848

**Comment by SlowestLoris** [comment]
The minimum age for Github use is 13 as listed by the terms and services. We're sorry, but we've reported you.
