### ISSUE TITLE
Audit Log Spam

### ISSUE THREAD

**Issue by MisterCookiez** [BumpBotDiscord/bugs-suggestions#4]
Is there a way to prevent constant spamming of **audit logs**? For example, storing each link in a database with their respective servers?

<img width="668" alt="screen shot 2018-01-07 at 11 11 29 am" src="https://user-images.githubusercontent.com/30220624/34651238-9901022c-f39b-11e7-916c-b8391220c2ed.png">

**Comment by SlowestLoris** [comment]
If you don't remove the invite it will automatically fetch the invite anyways...

**Comment by MisterCookiez** [comment]
Here's a screenshot when using **premium** and **normal** bumps through a specific amount of time.

<img width="674" alt="screen shot 2018-01-07 at 12 25 14 pm" src="https://user-images.githubusercontent.com/30220624/34651962-f0f9a34e-f3a5-11e7-813a-c903cb06a73f.png">

**Comment by SlowestLoris** [comment]
Solution Completed, will be implemented along with the newest update.
